### ISSUE TITLE
gen-docs is not working with -i

### ISSUE THREAD

**Issue by nlarzon** [trussworks/pre-commit-hooks#2]
With adr-log you can change a README with the hooks in it

`adr-log -d ./doc/adr/ -i README.md `

That doesn't seam to work with gen-docs hook

**Comment by chrisgilmerproj** [comment]
Can you provide an example of how you're using this? Please include the section of your `.pre-commit-config.yaml` file that you are using. Would also be good to know if you're using the `adr-log` command outside of the pre-commit tool. We want to verify if its an issue with `adr-log` or with the pre-commit hook script.

**Comment by nlarzon** [comment]
With  adr-log you can pass an argument to:

-i:     Edit the <input> file directly, injecting the log at .
          Using only the -i flag, the tool will scan the current working directory for all *.md files and
          inject the resulting adr-log into the default index.md file.
          (Without this flag, the default is to print the log to stdout.)

This way you can insert to an existing README file.

```yaml
  - repo: git://github.com/trussworks/pre-commit-hooks
    rev: v0.0.1
    hooks:
      - id: gen-doc
         args ["doc/adr", "README.md"]
```
-d "doc/adr" , -i "README.md"

I realise this is a comer case and maybe not worth implementing.
